# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_auto_20171120_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_by', models.CharField(max_length=255)),
                ('quote', models.CharField(max_length=255)),
                ('favorites', models.ManyToManyField(related_name='favorites', to='login_app.User')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='login_app.User')),
            ],
        ),
    ]
